# Generated by Django 3.1.7 on 2021-05-17 18:16

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_text', models.CharField(max_length=200)),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media'), upload_to='')),
            ],
        ),
    ]
