version: "3.8"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY="x%wsfaus-eob+a&j@00tsm(#+lf(f6js@00vfk+sfepdb_^s-s"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    entrypoint: ./entrypoint.sh
    depends_on:
      - db
