# Generated by Django 3.1.7 on 2021-03-29 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catuestion_text', models.CharField(max_length=200)),
                ('publication_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Cachoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cachoice_text', models.CharField(max_length=200)),
                ('cavotes', models.IntegerField(default=0)),
                ('catuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catpolls.catuestion')),
            ],
        ),
    ]
