# Generated by Django 3.1.7 on 2021-05-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catpolls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catuestion',
            name='catuestion_image',
            field=models.ImageField(default='polls-img/img23.jpg', upload_to='polls-img/'),
            preserve_default=False,
        ),
    ]
