- hosts: test_dataops_instance
  become: yes

  vars_files:
    - vars.yml

  pre_tasks:
    - name: "apt-get update"
      apt:
        update_cache: yes
        cache_valid_time: 3600

  tasks:
    - name: "install nginx"
      apt:
        name: ['nginx']
        state: latest

    - name: Install dependencies for PostgreSQL
      apt: name={{ item }} update_cache=true state=latest
      with_items:
        - bash
        - openssl
        - libssl-dev
        - libssl-doc
    
    - name: Install PostgreSQL 
      apt: name={{ item }} update_cache=true state=present
      with_items:
        - postgresql
        - postgresql-contrib
        - libpq-dev
        - python3-psycopg2
    
    - name: Ensure the PostgreSQL service is running
      service: name=postgresql state=started enabled=yes

    - name: Create the database specified in vars
      become: true
      become_user: postgres
      postgresql_db: name={{ db_name }}
           template='template0'
           state=present

    - name: Ensure user has access to the new database
      become: true
      become_user: postgres
      postgresql_user: db={{ db_name }}
           name={{ db_user }}
           password={{ db_password }}
           priv=ALL
           state=present

    - name: Ensure user does not have unnecessary permissions
      become: true
      become_user: postgres
      postgresql_user: name={{ db_user }}
          role_attr_flags=NOSUPERUSER,NOCREATEDB
          state=present

    - name: Allow remote connection to PostgreSQL database
      copy:
        src: pg_hba.conf
        dest: /etc/postgresql/14/main/

    - name: Allow all adresses to listen
      lineinfile:
        path: /etc/postgresql/14/main/postgresql.conf
        line: "listen_addresses = '*'"

    - name: Restart PostgreSQL
      service: name=postgresql state=restarted 

